### ISSUE TITLE
Doesn't work on jailbreaked KPW3 with FW Ver. 5.6.5

### ISSUE THREAD

**Issue by bt4wang** [koreader/kpvbooklet#20]
Just got my workmate's KPW3(5.6.5) jailbreaked via serial. Then I found that KPVBooklet v0.6.1 doesn't work. I've tried to uninstall and reinstall it times, but no good news.

Please contact me if any further information was needed. 

Regards.

**Comment by bt4wang** [comment]
Update, KPVBooklet v0.6.1 works fine on KPW2(5.6.5), but not on KPW3(5.6.5).

**Comment by bt4wang** [comment]
Update2. On KPW3(5.6.5), MR Installer doesn't perform a correct update, only shows "Checking kpvbooklet 0.6.1.1, destorying package".

**Comment by bt4wang** [comment]
Update 3. Problem solved by repack this baby with Kindletool 1.6.4. Please release an official package compatible with KPW3(5.6.5).

**Comment by chrox** [comment]
Thanks for the info, new version is coming. :)
