### ISSUE TITLE
`Update kindle` is gray, in kpw1 5.6.1.1

### ISSUE THREAD

**Issue by qdwang** [koreader/kpvbooklet#21]
I've updated my kindle from 5.4.x to 5.6.1.1.

KULA works fine with koreader.

But kpvbooklet can't work or be installed.

After putting the update-xxx.bin to root, the `Update kindle` button is just gray.

What the problem may be here?

**Comment by chrox** [comment]
Which version of KPVBooklet did you try? Version v0.6.2 may have a slight difference with v0.6.1 on supporting the latest Kindle firmware.

**Comment by NiLuJe** [comment]
Can't install normal packages that way on FW 5.6.x. You'll have to use MRPI through KUAL. See the relevant threads on the mobileread forum.

**Comment by qdwang** [comment]
I'm now using KUAL...
