### ISSUE TITLE
PDFs open in a native app and epubs give me an error

### ISSUE THREAD

**Issue by otichy** [koreader/kpvbooklet#24]
KPVBooklet v0.6.2
koreader-stable-v2015.11
Kindle PW: 5.7.3 (but the same on 5.6.5)

KPVBooklet installs fine through KUAL & Mr Packages, but PDFs still open in native app, not Koreader and .epubs give me "Application Error - The Selected application could not be started". 
I have terminal and su, so I can provide any logs necessary.

**Comment by chrox** [comment]
You can try to uninstall kpvbooklet first and then reinstall it again.

**Comment by otichy** [comment]
ok, feeling a bit stupid, that did the trick. thanks!
