### ISSUE TITLE
Bug：KPVBooklet v0.6.2 can not support for the latest firmware version 5.7.4

### ISSUE THREAD

**Issue by Quemada** [koreader/kpvbooklet#25]
Bug：KPVBooklet v0.6.2 can not support for the latest firmware version 5.7.4
My device is kindle paperwhite3 & kindle basic

**Comment by bel3atar** [comment]
It stopped working on the PW2 as well.

**Comment by chrox** [comment]
Could you describe what did you observe on 5.7.4 with kpvbooklet?

**Comment by bel3atar** [comment]
@chrox It's just as if kpvbooklet is not installed: the stock reading app opens and the reading progess is reset.

**Comment by Quemada** [comment]
@chrox When I updated the firmware version 5.7.4 on my kpw3, I uninstall KPVBooklet v0.6.2 and then reinstall it. I've done it twice, but PDF Files could not be opened with Koreader. My Koreader version is koreader-nightly-20151213. I didn't find this issue in other firmware versions , like 5.7.2, 5.7.2.1, 5.7.3 & 5.7.3.1

**Comment by hyln9** [comment]
@NiLuJe

**Comment by houqp** [comment]
@hyln9 , I think @chrox is taking a look.

**Comment by hyln9** [comment]
Well, once I get my Voyage updated, I'll be happy to participate in. I still remember the days when my nick name was "variousvirgil" and when I was debugging #10 with @chrox :-)

**Comment by chrox** [comment]
I'll take a look after I get my Kindle Voyage updated to 5.7.4.

**Comment by Quemada** [comment]
Thank you @chrox ! By opening the KUAL, I can enter the koreader filemanager now. PDF files can be opened in this way.

**Comment by mfirewire** [comment]
I have the same problem. After upgrading KPW2 to 5.7.4, PDF file can not opened by KOReader by KPVBooklet. Pls help to update KPVBooklet. Thanks!

**Comment by chrox** [comment]
Latest release v0.6.3 should fix this problem, tested on Kindle Voyage 5.7.4.

**Comment by bel3atar** [comment]
That fixed it.
