### ISSUE TITLE
pkvbootlet can not be installed on Kindle Touch 5.3.7.3

### ISSUE THREAD

**Issue by 1900forever** [koreader/kpvbooklet#26]
Just recently upgrade my Kindle Touch from 5.3.7.2 to 5.3.7.3, then koreader needs to be reinstalled.

I tried to install pkvbootlet first, when rebooting, it says error 7.

**Comment by NiLuJe** [comment]
You're Doing It Wrong(TM).

Never rebbot with a custom .bin update package. Always use the "Update Your Kindle" link in the settings menu (or MRPI, if applicable).

**Comment by chrox** [comment]
Please refer to the latest [Jailbreak FAQ](http://www.mobileread.com/forums/showthread.php?t=275877) and [MRPI instructions](http://www.mobileread.com/forums/showthread.php?t=251143).
