### ISSUE TITLE
KPVBooklet does not install on KOA (Kindle Oasis)

### ISSUE THREAD

**Issue by homeceo43** [koreader/kpvbooklet#27]
My KOA (jailbroken) is still on the original downgrade firmware 5.7.4 (have not upgraded back up to 5.8.1.)

I'm wanting to use KOReader on the KOA.

KUAL does not work on KOA, and Kindle Menu does not install without KUAL .

I tried installing KPVBooklet using ;log mrpi searchbar command to see if I could install it without KUAL.

I made sure that I have installed the latest 'hotfix' and also the latest MobileRead Package Installer. I also made sure I had the latest kpvbooklet install bin and put it in the mrpackages folder.

I typed ;log mrpi in the search bar and the installer runs and this displays:

"Launching MR Installer"

then
"checking kpvbooklet 0.6.3 I"
"destroying package"

then
"restarting UI"

So I guess that KPVBooklet is a kindlet and cannot be installed on the KOA either?

Here is the mrinstaller.log:

**** **** **** ****

[2016-07-16 @ 07:52:50 -0700] :: [MRPI r13359] - Beginning the processing of package 'update_kpvbooklet_0.6.3_install.bin' (kpvbooklet 0.6.3 I) . . .

Package 'update_kpvbooklet_0.6.3_install.bin' (kpvbooklet 0.6.3 I) is not targeting your device [0GC vs. 11 0F 10 24 1B 1C 1D 1F 20 D4 5A D5 D6 D7 D8 F2 17 60 62 5F 61 C6 DD 13 54 53 0G1 0G7 0G6 0G2 0G5], skipping . . . :(

**** **** **** ****

I'm wanting to use KOReader on the KOA. It seems it is not possible because I cannot install any launchers (KUAL, Kindle Menu, or KPVBooklet).

KPVBooklet and KOReader work great on my Kindle Voyage.

**Comment by houqp** [comment]
I think none of us has oasis yet :P If none of the launchers are working, then you won't be able to run KOReader. Mobileread is a better place to discuss launcher issues.

**Comment by NiLuJe** [comment]
For the record, this was also asked on MR, and moved here at my request ;).

My concern being that simply repacking the update package won't necessarily be enough to make it behave on an Oasis.
But, as I'm not familiar with the internals of Booklets, that may not actually hold true, and repacking might in fact be the only thing necessary ;).

**Comment by houqp** [comment]
interesting, i was not following oasis. what's new in the firmware what prevents kual from working?

**Comment by chrox** [comment]
I just uploaded a repacked update bin of kpvbooklet with a small fix to find new document settings file. @homeceo43 Could you try installing the new v0.6.4 and report the result here?

Hope the [booklet launching API](https://github.com/koreader/kpvbooklet/blob/master/src/com/github/chrox/kpvbooklet/KPVBooklet.java#L111) doesn't change in the Kindle Oasis, because it is so simple and elegant:
```java
public void start(URI contentURI)
```.

**Comment by chrox** [comment]
The active content framework might already be abandoned by lab126. But the booklet framework seems quite stable and extensible. How about porting KUAL to a booklet?

**Comment by homeceo43** [comment]
Thank you @chrox  (and thank you @NiLuJe for the further explanation)

Yes, KPVBooklet did install using v.0.6.4.

The epub file now shows in on the Kindle's home page as a book. It the shows the title (or rather actual filename) and right under that it shows "Kindle Document, EPUB".

I tapped it to open and the screen blinks blank then goes back to the home page. I restarted the Kindle; same behavior.

I think KOReader is crashing. I did reinstall KOReader, but it still crashes. I'm using the stable version of KOReader (https://github.com/koreader/koreader/releases/tag/v2015.11-stable)

Here is the crash.log from KOReader:

*******
./luajit: frontend/device/kindle/device.lua:363: unknown Kindle model B0
stack traceback:
	[C]: in function 'error'
	frontend/device/kindle/device.lua:363: in main chunk
	[C]: in function 'probeDevice'
	frontend/device.lua:37: in main chunk
	[C]: in function 'require'
	frontend/ui/uimanager.lua:1: in main chunk
	[C]: in function 'require'
	./reader.lua:92: in main chunk
	[C]: at 0x0000be8d
******

I also have a PDF file on the Kindle; when I tap it to open, it is the same behavior as the epub; KOReader crashes.

**Comment by homeceo43** [comment]
Well, I decided I probably needed to also install the latest KOReader, koreader-kindle-arm-linux-gnueabi-v2015.11-533-g1d2150c.zip ......... and it WORKS!

Both the epub and the PDF open with KOReader and KOReader does not crash with this build.

On the Kindle home page, the PDF file does show percent read.

The epub file on the home page list does not show percent read.

The epub shows:
Title of Book
Kindle Document, EPUB

The PDF shows:
Title of Book
Author
PDF, % READ

My Kindle Oasis is still on the downgraded firmware 5.7.4 (would like to update it back to 5.8.1, but I also want to make sure KPVBooklet and KOReader would continue to work).

I have a Kindle Voyage that is back up to firmware 5.8.1. (KPVBooklet and stable version KOReader on this one, works fine.)

The epub shows in the Voyage home page list this way:
Title of Book
% read, DOC

On the Voyage, the PDF shows this way:
Title of Book
Author
% read, PDF

Thank you, and please let me know what testing I could do for you.

**Comment by homeceo43** [comment]
Observations with KOReader on the Kindle Oasis:

Oasis still on downgraded firmware 5.7.4; this KOReader build installed: koreader-kindle-arm-linux-gnueabi-v2015.11-533-g1d2150c.zip

The physical page turn buttons do not work while using KOReader.

You know the Oasis has that accelerometer feature where you can flip the Oasis upside down to hold in your left hand, the screen flips orientation and the physical page buttons can be used with left hand.

The screen does flip orientation, the book flips orientation, KOReader menus also flip orientation (so they are not upside down when holding the reader in left hand) however KOReader still thinks it is right side up tap zone-wise -- the tap zones do not flip orientation. Tap the left side of the screen pages forward; tap right side of screen pages back. Tap top of screen and page number disappears, tap top of screen again page number reappears (page number is what I have showing only, not the other stuff or progress bar). Tap the bottom of the screen brings up the KOReader menu, but tapping anything the menu just makes the menu disappear.


I don't use the PagePress buttons on my Kindle Voyage, but turned them on to see how they worked with KOReader.

Voyage on firmware 5.8.1; using KOReader stable build on the Voyage:
Yes, the PagePress buttons do work to page forward and back in KOReader.

**Comment by NiLuJe** [comment]
@chrox: That's been at the back of my mind for a while, yeah... Unfortunately, it's pure luck that I've been able to do anything with the KUAL code, I have basically zero knowledge of Java, so I'm not quite sure how trivial (or not) that would be...

Guess I'll start by taking a deeper look...

@homeceo43: Yeah, I only implemented the basics (screen/touch) based on what was readily transparent from a kernel/system log, since none of us have the device ;).
In the same vein, I'm not quite sure *which* battery we're currently tracking... By guess would be the actual one in the device, not the cover's.

I had even forgotten that there were physical buttons, so, there you go ;D.
Thanks for testing the accelerometer, too, I did not expect to have to deal with it... No idea how, though ;D.

**Comment by homeceo43** [comment]
@NiLuJe: The device battery is tracked in KOReader, whether out of the cover, or in the cover. When you connect the cover and the device battery starts charging from the cover battery and the device battery percentage goes up, in KOReader it shows whatever is the device battery percentage.

**Comment by NiLuJe** [comment]
@homeceo43: Great, that's how I imagined it would behave, and I think I'm okay with leaving it at that ;).

**Comment by homeceo43** [comment]
@chrox:

I unistalled KPVBooklet 0.6.4; then I updated my Kindle Oasis from firmware 5.7.4 back up to 5.8.1.

I then reinstalled KPVBooklet 0.6.4.

Now, on the Kindle Oasis home screen the book list shows percentage read for epubs: 
Title of Book
%, DOC

and it also shows the read progress on the little dots.

Thank you, thank you! for fixing KPVBooklet to also install on the Kindle Oasis.

And thank you @NiLuJe for suggesting I ask the question here.

**Comment by NiLuJe** [comment]
@chrox:

You can laught at my pitiful attempts [https://bitbucket.org/NiLuJe/kindlelauncher/](here).

Turns out, the API is only *mostly* stable... BookletContext.getUIContainer(), which we kinda need, got mercilessly obfuscated on newer FW... -_-".

**Comment by chrox** [comment]
@NiLuJe Take a look [here](https://github.com/koreader/kpvbooklet/blob/master/src/com/github/chrox/kpvbooklet/ccadapter/CCAdapter.java#L45-L57) on how to enumerate all obfuscated methods of a class and get the one we want with Java reflection:

```java
			Class[] signature = {String.class, String.class, int.class, int.class};
			Method[] methods = ContentCatalog.class.getDeclaredMethods();
			for (int i = 0; i < methods.length; i++) {
				Class[] params = methods[i].getParameterTypes();
				if ( params.length == signature.length ) {
					int j;
				    for (j = 0; j < signature.length && params[j].isAssignableFrom( signature[j] ); j++ ) {}
				    if ( j == signature.length ) {
				    	perform = methods[i];
				    	break;
				    }
				}
			}
```

**Comment by NiLuJe** [comment]
@chrox: Wish I had checked here sooner, but I came to the same solution while looking at that very same bit of code in KPVBooklet ;).

In any case, it does the job perfectly well, thanks :).

**Comment by chrox** [comment]
Looks great! 
Could you fix [this](https://bitbucket.org/ixtab/kindlelauncher/src/d9549547494592d9866d2cba94c58bde0d7a526b/src/com/mobileread/ixtab/kindlelauncher/resources/booklet/uninstall/appreg.uninstall.sql?at=master&fileviewer=file-view-default#appreg.uninstall.sql-1:3):
```
DELETE FROM "handlerIds" WHERE handlerId='com.github.koreader.kpvbooklet' or handlerId='com.mobileread.ixtab.kindlelauncher';
DELETE FROM "properties" WHERE handlerId='com.github.koreader.kpvbooklet' or handlerId='com.mobileread.ixtab.kindlelauncher';
DELETE FROM "associations" WHERE handlerId='com.github.koreader.kpvbooklet' or handlerId='com.mobileread.ixtab.kindlelauncher';
```
It will also uninstall kpvbooklet stuff, I hope it's a copy&paste typo. :)

**Comment by NiLuJe** [comment]
@chrox: Wow, no idea how that slipped through, thanks for catching that!

**Comment by homeceo43** [comment]
@NiLuJe: I will open a new issue here: https://github.com/koreader/koreader/issues regarding the physical page buttons not working when using KOReader on the Kindle Oasis. Probably is more appropriate place. 

Great work on the KUAL booklet. I was able to install it successfully on my KOA.

**Comment by chrox** [comment]
Closing this as the OP has solved the problem.
