### ISSUE TITLE
The new version 0.6.6 still isn't fully functioning.

### ISSUE THREAD

**Issue by CaesarW** [koreader/kpvbooklet#32]
__Device: Kindle Paperwhite 3__
__Firmware: 5.9.10 jailbroken__
__KPVBooklet Version: 0.6.6__
### Problem Description:
Few days ago I installed the 0.6.5 version and with the hope to use the KUAL extension. I installed and it doesn't work. Main problem should be the key "bin" folder is not installed in KUAL extension properly. I replied both in the issue #30 #29, and got replied. I installed the newer version @chrox provided and the problem still occurs. Later it is figured out that the bin folder is ignored by git. But when I see the new release 0.6.6 (in the release page), and installed it, hoping the "bin" folder is included. But actually not. Why is it so hard to include a folder into an install bin file? Not everyone like me will check issue page after installation to find that the bin folder is not included. Most people prefer to install with only one step. Why not make the whole installation process finish in one package?

PS: Maybe I am a bit too angry about it.😂😂 If there're some further problem, maybe I can help since I am also a developer *at some point*. 😊

**Comment by chrox** [comment]
I'm sorry about the confusion it may caused. I will check on that tonight.

**Comment by chrox** [comment]
```diff
diff --git a/install.ffs b/install.ffs
index 6176790..bdea9fd 100755
--- a/install.ffs
+++ b/install.ffs
@@ -58,8 +58,10 @@ if [ "$VERSION" \> "5.4" ]; then
 fi
 
 progress 80 "Installing KUAL Extension"
-mkdir -p /mnt/us/extensions
-cp -r extensions/kpvbooklet /mnt/us/extensions/ || fail "Unable to copy KUAL Extension"
+mkdir -p /mnt/us/extensions/kpvbooklet/bin
+cp extensions/kpvbooklet/bin/booklet.sh /mnt/us/extensions/kpvbooklet/bin/
+cp extensions/kpvbooklet/config.xml /mnt/us/extensions/kpvbooklet
+cp extensions/kpvbooklet/menu.json /mnt/us/extensions/kpvbooklet || fail "Unable to copy KUAL Extension"
 
 progress 90 "Mounting ro"
 mntroot ro || fail "Unable to mount ro"
```

It turns out that the install script of the Kindle update system is not regular shell script and the `cp -r` does not really copy the directory recursively so we have to copy file by file like in this patch. Hopefully we newly uploaded 0.6.6 could solve this problem. The KUAL extension should also work. Tested on Kindle Voyage 5.8.9.

**Comment by CaesarW** [comment]
Please upload the fixed version if possible 😉😉

**Comment by chrox** [comment]
Please check the released 0.6.6 version [here](https://github.com/koreader/kpvbooklet/releases/tag/v0.6.6). It includes the patch mentioned above.

**Comment by CaesarW** [comment]
But it says that 0.6.6 release is uploaded 3 days ago which is earlier than the last commit.

**Comment by Frenzie** [comment]
@CaesarW I would assume @chrox replaced the uploaded file to include that commit. (Also it says yesterday? Where are you getting 3 days ago from?)

**Comment by CaesarW** [comment]
![Screenshot](https://i.imgur.com/FGEsGPA.png)

maybe the fault of my Github app?

**Comment by CaesarW** [comment]
![Screenshot](https://i.imgur.com/QbpD0VQ.png)


sorry guys. my fault.😫😫

**Comment by CaesarW** [comment]
so just update kpvbooklet with the latest bin without uninstall the former version?

**Comment by cytown** [comment]
Yes, you should try the newest one, and no need uninstall.

**Comment by cytown** [comment]
@chrox thx guy, you rocks.

**Comment by zivilyyyn** [comment]
I have the same issue. My Device is KPW3-32G with 5.9.6 firmware. I have installed KOReader (v2015.11-1897) and KPVBooklet (v0.6.6). No KUAL menu showed. Mannually and extensions folder into the extensions directory, then it works. But I only have PDF and txt options, no epub option shows.
![screenshot_2018_10_26t02_36_33 0800](https://user-images.githubusercontent.com/32798348/47522962-73586880-d8c9-11e8-8569-a14c794200a8.png)
