### ISSUE TITLE
Stopped working on new firmware 5.9.2.0.1

### ISSUE THREAD

**Issue by DesertHuYang** [koreader/kpvbooklet#34]
Just updated to the latest fw, and unluckily kpvbooklet and KUAL can't start.
Any possibility to fix it? Or run KOReader without kpvbooklet?

**Comment by DesertHuYang** [comment]
I've found an alternative way to start KOReader. Just use USBNetwork tweak and run the starting command provided in the "menu.lst" files. Should be appliable for all KUAL tweaks. Hoping you guys would soon find a new way to solve the problem.
I regret UPDATING to this fw.

**Comment by mzelyony** [comment]
KPVbooklet stopped working for me to after upgrading to 5.9.4. I am on PW2

**Comment by mzelyony** [comment]
Reinstall of kpvbooklet helped

**Comment by mmxxmm** [comment]
KOA 5.9.4
KPVBooklet 0.66 installed successfully.But PDF files still open in default reader.
uninstall and reinstall not helped.

**Comment by usernatilds** [comment]
Not work in 5.8.1 for open pdf, uninstall and reinstall in kual not helped

**Comment by NiLuJe** [comment]
See #43
