### ISSUE TITLE
Support for 5.8.1

### ISSUE THREAD

**Issue by usernatilds** [koreader/kpvbooklet#35]
Is possible?

**Comment by usernatilds** [comment]
I use Kindle Papperwhite

**Comment by Frenzie** [comment]
I'll close this in favor of #34 . @NiLuJe Do you know anything about this stuff?

**Comment by NiLuJe** [comment]
@Frenzie : I haven't followed all that too closely, but from what I gathered, some recent/current FW versions started obfuscating the Booklet API, which basically royally fucks with the 'universal' booklet approach. You instead have to RE the required bits of API build-per-build, àla JBPatch, and it's basically awful and a huge mess.

I know @coplate tried/tries to maintain KUAL builds on some of those FW, but that's it ;).

**Comment by coplate** [comment]
@Frenzie : like @NiLuJe  said, amazon has started obfuscating the Booklet like they did earlier with the Kindlets. 

[ In this sample ](https://github.com/coplate/KUAL_Booklet/commit/d1b04906b8ee3701231cb2c0fc4e225f028e0e3c#diff-52d30459829c78910665e0e989a86b71) I took one options, and stopped using the `create ` and `start ` functions that they obfuscated, but manually built up the objects in a thread started by the constructor.


the other method I took was just to hijack booklet constructor to execute a c++ program that could do a replacement, and then exit, I think if they keep obfuscating that will likely last longer.

I looked into setting up the associations sqlite program to try to run the c++ program directly, but I never could make it work.   

Then I got back into Warcraft, and mostly let this drop.

**Comment by NiLuJe** [comment]
Ah, WoW, the great timekiller... ^^.

Thanks for dropping by, and your work on all that mess, btw ;).

**Comment by usernatilds** [comment]
@NiLuJe, If I upgrade the firmware of kindle to the latest version 5.9.5.1 , do I miss the jailbreak? Compensate to upgrade? Are there any more features? Or should I keep a 5.8.1 firmware?

**Comment by Frenzie** [comment]
I don't know about Kindle specifically, but on general principle I would avoid upgrading if you depend on third-party workarounds.

**Comment by usernatilds** [comment]
@Frenzie, actually i use BB Filter to avoid ota kindle updates.

**Comment by NiLuJe** [comment]
See #43 (where I just xref'ed this for @coplate's helpful explanation).
