### ISSUE TITLE
issues with 5.10.2 on oasis1

### ISSUE THREAD

**Issue by suifeng63** [koreader/kpvbooklet#40]
hello，Thank you for what you did for kindle。I need your help，i have kindle oasis1，Firmware version is 5.10.2. i can through koreder file browser open Epub format e-book，but i  can not through kpvbooklet v0.6.1-v0.6.6 transfer koreder，so i can not open epub format e-book in main interface 。please update kpvbooklet to be applicable 5.10.2，thank you very much。

**Comment by aerickson** [comment]
Please run the `showlog` command while ssh'ed into your device and post the output?

**Comment by Keybird0** [comment]
I have tryed this "https://github.com/aerickson/kpvbooklet/releases/tag/v0.6.7.pre3" , but it didn't work.

**Comment by aerickson** [comment]
Please follow https://github.com/koreader/kpvbooklet#troubleshooting when reporting bugs. It's impossible to help otherwise.

The `showlog` command output requires SSH access to your device. See https://wiki.mobileread.com/wiki/Kindle_Touch_Hacking#USB_Networking for instructions.

**Comment by Keybird0** [comment]
`190211:162556 [51155.349547] max77696-rtc max77696-rtc.0: --> 2019-02-11 Mon 08:24:56
190211:162556 [51155.350604] max77696-rtc max77696-rtc.0: written RTCINTM 0x3F [0]
190211:162557 luajit: W def:lipc:method=LipcOpenEx service=com.github.koreader.ambientbrightness:Method has been deprecated.
190211:162557 powerd[2472]: W lipc:pnr:prop=alsLux:Property not registered
190211:162559 luajit: W def:lipc:method=LipcOpenEx service=com.github.koreader.ambientbrightness:Method has been deprecated.
190211:162559 powerd[2472]: W lipc:pnr:prop=alsLux:Property not registered
190211:162601 luajit: W def:lipc:method=LipcOpenEx service=com.github.koreader.ambientbrightness:Method has been deprecated.
190211:162601 powerd[2472]: W lipc:pnr:prop=alsLux:Property not registered
190211:162603 cvm[27127]: I WishListLipcAdapter:Information::RCM triggered, Updating wishlist data..
190211:162603 cvm[27127]: I WishListManager:Information::Wishlist not enabled...
190211:162603 rcm_main[2461]: I refreshcache:trySortClients:status=16:Unable to lock mutex
190211:162603 luajit: W def:lipc:method=LipcOpenEx service=com.github.koreader.ambientbrightness:Method has been deprecated.
190211:162603 powerd[2472]: W lipc:pnr:prop=alsLux:Property not registered
190211:162605 luajit: W def:lipc:method=LipcOpenEx service=com.github.koreader.ambientbrightness:Method has been deprecated.
190211:162605 powerd[2472]: W lipc:pnr:prop=alsLux:Property not registered
190211:162607 luajit: W def:lipc:method=LipcOpenEx service=com.github.koreader.ambientbrightness:Method has been deprecated.
190211:162607 powerd[2472]: W lipc:pnr:prop=alsLux:Property not registered
190211:162609 luajit: W def:lipc:method=LipcOpenEx service=com.github.koreader.ambientbrightness:Method has been deprecated.
190211:162610 powerd[2472]: W lipc:pnr:prop=alsLux:Property not registered
190211:162612 luajit: W def:lipc:method=LipcOpenEx service=com.github.koreader.ambientbrightness:Method has been deprecated.
190211:162612 powerd[2472]: W lipc:pnr:prop=alsLux:Property not registered
190211:162614 luajit: W def:lipc:method=LipcOpenEx service=com.github.koreader.ambientbrightness:Method has been deprecated.
190211:162614 powerd[2472]: W lipc:pnr:prop=alsLux:Property not registered
190211:162616 luajit: W def:lipc:method=LipcOpenEx service=com.github.koreader.ambientbrightness:Method has been deprecated.
190211:162616 powerd[2472]: W lipc:pnr:prop=alsLux:Property not registered
190211:162618 cvm[27127]: I FreeTimeServiceImpl:Syncing freetime:reason=RCM trigger:Freetime/Household not supported. Ignoring sync.
190211:162618 rcm_main[2461]: I refreshcache:trySortClients:status=16:Unable to lock mutex
190211:162618 luajit: W def:lipc:method=LipcOpenEx service=com.github.koreader.ambientbrightness:Method has been deprecated.
190211:162618 powerd[2472]: W lipc:pnr:prop=alsLux:Property not registered
190211:162620 luajit: W def:lipc:method=LipcOpenEx service=com.github.koreader.ambientbrightness:Method has been deprecated.
190211:162620 powerd[2472]: W lipc:pnr:prop=alsLux:Property not registered
190211:162622 luajit: W def:lipc:method=LipcOpenEx service=com.github.koreader.ambientbrightness:Method has been deprecated.
190211:162622 powerd[2472]: W lipc:pnr:prop=alsLux:Property not registered
190211:162624 luajit: W def:lipc:method=LipcOpenEx service=com.github.koreader.ambientbrightness:Method has been deprecated.
190211:162624 powerd[2472]: W lipc:pnr:prop=alsLux:Property not registered
190211:162626 luajit: W def:lipc:method=LipcOpenEx service=com.github.koreader.ambientbrightness:Method has been deprecated.
190211:162626 powerd[2472]: W lipc:pnr:prop=alsLux:Property not registered
190211:162628 luajit: W def:lipc:method=LipcOpenEx service=com.github.koreader.ambientbrightness:Method has been deprecated.
190211:162628 powerd[2472]: W lipc:pnr:prop=alsLux:Property not registered
190211:162630 luajit: W def:lipc:method=LipcOpenEx service=com.github.koreader.ambientbrightness:Method has been deprecated.
190211:162630 powerd[2472]: W lipc:pnr:prop=alsLux:Property not registered
190211:162632 luajit: W def:lipc:method=LipcOpenEx service=com.github.koreader.ambientbrightness:Method has been deprecated.
190211:162632 powerd[2472]: W lipc:pnr:prop=alsLux:Property not registered
190211:162633 cvm[27127]: E ContentPackageController:Error::updateMasterManifest failed
190211:162633 rcm_main[2461]: I refreshcache:trySortClients:status=16:Unable to lock mutex
190211:162634 luajit: W def:lipc:method=LipcOpenEx service=com.github.koreader.ambientbrightness:Method has been deprecated.
190211:162635 powerd[2472]: W lipc:pnr:prop=alsLux:Property not registered
`
this is  my showlog output(just a part), really hope can solve this problem, the kpvbooklet really useful, i think. The entire output if you need i can send to your email. @aerickson

**Comment by Keybird0** [comment]
you can download the entire showlog command output via this url: https://gofile.io/?c=aiol2i
Expecting your good news!
@aerickson

**Comment by aerickson** [comment]
Thanks for the log. I think I found the region with the problem. 

I'm not sure what the issue is. Perhaps others might know.

What kind of file is it? Do other types of files work?

```
190211:161924 cvm[27127]: I BookletImplementation:Starting:name=com.github.koreader.kpvbooklet:
190211:161924 cvm[27127]: I ReaderBooklet:Information::ReaderBooklet start
190211:161924 cvm[27127]: I GlobalKeyEventDispatcher:Information::Subscribing listener to whispertouch eventscom.github.koreader.kpvbooklet
190211:161924 cvm[27127]: I ReaderBooklet:Information::Posting reader booklet starting event
190211:161924 cvm[27127]: I ReaderStateManager:Information::De-registered device; activeProfile is null.
190211:161924 cvm[27127]: I GlobalKeyEventDispatcher:Information::Unsubscribing listener from whispertouch eventscom.github.koreader.kpvbooklet
190211:161924 cvm[27127]: E ReaderBooklet:Error::Failed to start Reader
190211:161924 cvm[27127]: The selected item could not be opened. If you purchased this item from Amazon, delete the item and download it again from the Cloud on Home.
190211:161924 cvm[27127]: 	at com.amazon.ebook.booklet.reader.impl.ReaderSDKImpl.af(ReaderSDKImpl.java:759)
190211:161924 cvm[27127]: 	at com.amazon.ebook.booklet.reader.impl.ReaderSDKImpl.fo(ReaderSDKImpl.java:728)
190211:161924 cvm[27127]: 	at com.amazon.ebook.booklet.reader.impl.ReaderSDKImpl.i(ReaderSDKImpl.java:814)
190211:161924 cvm[27127]: 	at com.amazon.ebook.booklet.reader.ReaderBooklet.f(ReaderBooklet.java:394)
190211:161924 cvm[27127]: 	at com.amazon.ebook.booklet.reader.ReaderBooklet.e(ReaderBooklet.java:274)
190211:161924 cvm[27127]: 	at com.amazon.ebook.booklet.reader.ReaderBooklet.c(ReaderBooklet.java:195)
190211:161924 cvm[27127]: 	at com.amazon.ebook.booklet.reader.ReaderBooklet$1.run(ReaderBooklet.java:138)
190211:161924 cvm[27127]: 	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
190211:161924 cvm[27127]: 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
190211:161924 cvm[27127]: 	at java.awt.EventQueueProxy.dispatchEvent(Unknown Source)
190211:161924 cvm[27127]: 	at java.awt.AGUIEventDispatchThread.pumpOneEventForHierarchy(Unknown Source)
190211:161924 cvm[27127]: 	at java.awt.AGUIEventDispatchThread.pumpEventsForHierarchy(Unknown Source)
190211:161924 cvm[27127]: 	at java.awt.AGUIEventDispatchThread.pumpEvents(Unknown Source)
190211:161924 cvm[27127]: 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
190211:161924 cvm[27127]: 	at java.awt.EventDispatchThread.run(Unknown Source)
190211:161924 cvm[27127]: W BookletImplementation:LifecycleError:phase=go,code=0x50000001:
190211:161924 appmgrd[2480]: I appmgr_lipc:set_appmgr_go_result:propName=goresult,buf=1:1342177281:[{"replaceStr":"The selected item could not be opened. If you purchased this item from Amazon, delete the item and download it again from the Cloud on Home.","matchStr":"alertText"},{"replaceStr":"Unable to Open Item","matchStr":"alertTitle"}]:entry
190211:161924 appmgrd[2480]: I lipc:evts:name=appFailedInGo, origin=com.lab126.appmgrd, fparam=com.github.koreader.kpvbooklet:Event sent
190211:161924 appmgrd[2480]: I lipc:evts:name=appActivating, origin=com.lab126.appmgrd, fparam=-1:Event sent
190211:161924 appmgrd[2480]: I lipc:evts:name=appStateChange, origin=com.lab126.appmgrd, fparam=com.github.koreader.kpvbooklet:Event sent
190211:161924 appmgrd[2480]: I appmgr_history:app_state_change:lipc_id=com.github.koreader.kpvbooklet,state=PAUSED:
190211:161924 cvm[27127]: I StatusBarController:Information::reverting to cached app state in statusbar
190211:161924 winmgr[26253]: I WindowManager:handleAppLaunchFail:unpause display and clear timeouts:
190211:161924 appmgrd[2480]: I lipc:evts:name=appStateChange, origin=com.lab126.appmgrd, fparam=com.github.koreader.kpvbooklet:Event sent
190211:161924 appmgrd[2480]: I appmgr_lipc:custom_alert_displayed:app_lipc_id=com.github.koreader.kpvbooklet:show_simple_alert
```

**Comment by Keybird0** [comment]
I was opening an epub file at the time. when i open a pdf file will call the system's original open mode.

**Comment by cangshanwuyv** [comment]
I have the same question as you,KPV can't work any longer.If you have deal with the question,I hope you can tell me with the way.I'd appreciate you very much.By the way,sorry for my Chinese English.

**Comment by suifeng63** [comment]
我也是中国人啊，兄弟，我现在也没有找到方法，只有将就用了。


| |
赵涛
邮箱：z1129219893@163.com
|

签名由 网易邮箱大师 定制

On 03/10/2019 15:50, cangshanwuyv wrote:

I have the same question as you,KPV can't work any longer.If you have deal with the question,I hope you can tell me with the way.I'd appreciate you very much.By the way,sorry for my Chinese English.

**Comment by wenyanchao2018** [comment]
I have the same question as you

**Comment by NiLuJe** [comment]
See #43
