### ISSUE TITLE
the release is quite old, this doesn't work for 5.10.2

### ISSUE THREAD

**Issue by videni** [koreader/kpvbooklet#41]
can you build this for 5.10.2?

**Comment by Frenzie** [comment]
@aerickson Has made an updated builds available [here](https://github.com/aerickson/kpvbooklet/releases). I don't know if that makes any difference? 

(I'm only here as part of the KOReader organization.)

**Comment by videni** [comment]
@aerickson, hi , still not work.

**Comment by aerickson** [comment]
@videni Please post `showlog` output. Details on how to get it are at https://github.com/koreader/kpvbooklet#troubleshooting

What device are you on?

**Comment by NiLuJe** [comment]
See #43
