### ISSUE TITLE
ff没本钱怎么在手机一天赚500

### ISSUE THREAD

**Issue by ais716** [koreader/kpvbooklet#48]
没本钱怎么在手机一天赚500,首先没本钱的话，我觉得你就要先积累财富。

就我的经历来说吧，是一个学生党，我现在在做百度知道的兼职，按照回答的个数结算工资的，差不多一天三俩小时，一百多，我打字速度还行，但是我见过打字速度快的，一天能写三四百的大有人在，其实吧钱很好挣，只要你想做。

要对生活有信心，一切尽在你的掌握，有时候可能你跟财富仅一步之遥。

**Comment by Frenzie** [comment]
Spam.
