### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by terbooter** [koreader/kpvbooklet#7]
Kindle paperwhite firmware 5.3.9
I copied update_kpvbooklet_0.5.3_install.bin to kindle root
"Update Your Kindle" is disabled (grey)

**Comment by michaelcadilhac** [comment]
For what it's worth, I had to copy the file via mounting (USB) rather than ssh; I also renamed the file with a capital U, although the filesystem is case insensitive, so it's probably irrelevant.  I'm not sure what made it work.
